### PR TITLE
added ikfast plugin description

### PR DESCRIPTION
**Pull request by benmaidel**
this file was unstaged on cob4-2

### CODE REVIEW

**Comment by mathias-luedtke** [comment]
This file gets auto-generated by CMake rules..

**Comment by floweisshardt** [comment]
if it's auto-generated, we should not commit it but add it to .gitignore

**Comment by benmaidel** [comment]
@ipa-mdl told me that this file is auto generated during build. So no need to add it. Will close this pr

**Comment by floweisshardt** [comment]
it still makes sense to add it to .gitignore

**Comment by benmaidel** [comment]
see #84

**Comment by floweisshardt** [comment]
perfect!

**Pull request closed without merging**
