### PR TITLE
update to use non deprecated pluginlib macro

### PR DESCRIPTION
**Pull request by fmessmer**
same as https://github.com/ipa320/cob_perception_common/pull/86

### CODE REVIEW

**Review by mathias-luedtke — CHANGES_REQUESTED** [review]
This does not work properly, because it changes the name.
The `ADD_TYPED_PLUGIN` macro needs to get adjusted to use the new pluginlib macro.

**Comment by fmessmer** [comment]
@ipa-mdl updated the PR
(I thought I could short-cut the `#define` magic as the argument passing is not needed anymore...)

**Comment by mathias-luedtke** [comment]
Hmm, this changes the name as well.
I would keep it as-is for indigo and remove the package for kinetic.

**Comment by fmessmer** [comment]
`cob_kinematics` has been removed in `kinetic_dev` already....
I'm fine with @ipa-mdl's suggestion

**Pull request closed without merging**
