### PR TITLE
Multi distro travis

### PR DESCRIPTION
**Pull request by fmessmer**
kinetic_dev needed

### CODE REVIEW

**Comment by mathias-luedtke** [comment]
Is this just as test? What about #103?

**Comment by fmessmer** [comment]
> Is this just as test? What about #103?

#102 is for indigo_dev
#103 is for kinetic_dev

**Comment by mathias-luedtke** [comment]
So why do both build all distros?

**Comment by fmessmer** [comment]
> So why do both build all distros?

In **indigo_dev**, we try to build **indigo_dev** branch under **kinetic** (which fails :point_right: `allow_failures`)
In **kinetic_dev**, we try to build **kinetic_dev** branch under **kinetic** (works) but fails for **indigo**(:point_right: `allow_failures`)

**Comment by mathias-luedtke** [comment]
> In indigo_dev, we try to build indigo_dev branch under kinetic 

But why? We already know that this fails. There is not need to waste time (and travis jobs) on it.

**Comment by fmessmer** [comment]
Yes, I've been usure about what to do in such cases....
So we only would test indigo_dev under indigo/jade? and kinetic_dev under jade?/kinetic

**Comment by mathias-luedtke** [comment]
>  So we only would test indigo_dev under indigo/jade? and kinetic_dev under jade?/kinetic

* indigo_dev should get tested on indigo
* kinetic_dev should get tested on kinetic

Not sure how to handle jade.
IMHO it belongs to indigo_dev. (Otherwise kinetic_dev should be named jade_dev).

**Comment by fmessmer** [comment]
Ok, I will make the following changes (for all `kinetic_dev`-requiring repos!):
 - indigo_dev will test indigo and jade (as allow_failure)
 - kinetic_dev will only test kinetic (no indigo/jade, not even allow_failure)

Would that be ok?

**Pull request merged**
