### PR TITLE
debug info collision monitor and catch runtime exception

### PR DESCRIPTION
**Pull request by fmessmer**
@ipa-mdl

exception is required for simulation as there seems to be a race condition when using `sim_time` from gazebo

### CODE REVIEW

**Comment by mathias-luedtke** [comment]
I don't think that you have to print the collisions yourself, the verbose flag should enable it internally.

**Comment by fmessmer** [comment]
verbose only prints one collision pair, while with my modifications you could see all...as well as the penetration depth...

@ipa-mdl any objections in keeping my debug info? please merge otherwise...

**Comment by mathias-luedtke** [comment]
> @ipa-mdl any objections in keeping my debug info? 

Yes, it should be a param, which defaults to off.
And the state must be published before the debug prints.
Otherwise the stop might come too late.

**Comment by mathias-luedtke** [comment]
`verbose` should default to false as well.

**Comment by fmessmer** [comment]
@ipa-mdl I guess I considered your remarks accordingly...

**Review by mathias-luedtke — CHANGES_REQUESTED** [review]
Overall :+1: 

It would be great if you would clean-up the commit history.
Otherwise, just merge it :)

**Review by mathias-luedtke — APPROVED** [review]
I meant to approve..

**Pull request merged**
