### PR TITLE
update maintainer

### PR DESCRIPTION
**Pull request by fmessmer**
related to https://github.com/ipa320/care-o-bot/issues/46

### CODE REVIEW

**Comment by mathias-luedtke** [comment]
What is the ROS policy on removing already released packages?

**Review by ipa-rmb — DISMISSED** [review]
What is the replacement for cob_kinematics or why is it not used anymore? Is this done by moveit (plugins) now?

**Comment by fmessmer** [comment]
@ipa-rmb 
`cob_kinematic` is not used atm and was not used for quite a while...it is one of the packages that was always prone to be broken due to changes in the plugin API of moveit....it already is removed on the `kinetic_dev` branch anyway...

I do not know what happens to removed and already released packages....we have had such cases before and haven't had issues releasing...e.g. in `cob_extern`, `cob_substitute`, etc....the respective package do not appear on http://repositories.ros.org/status_page/ros_indigo_default.html anymore

**Comment by mathias-luedtke** [comment]
I don't see the need to remove it now from the indigo.

**Review by floweisshardt — APPROVED** [review]

**Review by ipa-rmb — APPROVED** [review]

**Pull request merged**
